-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 5bf6c09bfa1297d3692cadd621ef95f1284e33c0
    hooks:
    -   id: trailing-whitespace
        files: \.(js|rb|md|py|sh|txt|yaml|yml)$
    -   id: check-yaml
        files: \.(yaml|yml)$
    -   id: check-merge-conflict
        files: \.(js|rb|md|py|sh|txt|yaml|yml)$
    -   id: check-symlinks
-   repo: https://github.com/willthames/ansible-lint.git
    sha: v3.4.13
    hooks:
    -   id: ansible-lint
        files: \.(yaml|yml)$
        args:
        - --exclude=.travis.yml
        - --exclude=ansible/requirements.yml
        - --exclude=ansible/galaxy_roles
        - --exclude=test
